# name: 🔀 Sync mirror to Gitee

# on:
#   push:
#     branches:
#       - main
#       - docs
#   create:

# jobs:
#   mirror:
#     runs-on: ubuntu-latest
#     if: github.repository == 'fuzzy-ez/fuzzy'
#     steps:
#       - name: mirror
#         continue-on-error: true
#         if: github.event_name == 'push' || (github.event_name == 'create' && github.event.ref_type == 'tag')
#         uses: wearerequired/git-mirror-action@v1.2.0
#         env:
#           SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
#         with:
#           source-repo: 'git@github.com:fuzzy-ez/fuzzy.git'
#           destination-repo: 'git@gitee.com:fuzzy-ez/fuzzy.git'
